spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/custom/, classpath:/resources/,classpath:/static/
  mvc:
    static-path-pattern: /abc/**
  datasource:
    url: jdbc:mysql://localhost:3306/TEST_DB
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.purvar.springboot.demo.mapper
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    